a = input("Digite qualquer coisa: ")
print(f"O tipo primitivo desse valor é:{type(a)}")
print(f"Só tem espaços? {a.isspace()}")
print(f"é um numero? {a.isnumeric()}")
print(f"é alfabetico? {a.isalpha()}")
print(f"é alfanumerico? {a.isalnum()}")
print(f"esta em letra maisc? {a.isupper()}")
print(f"esta em minuscula? {a.islower()}")
print(f"esta capitalizada? {a.istitle()}")
